# Generated by Django 5.1.1 on 2024-10-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0002_remove_guest_qr_code_alter_guest_qr_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='qr_image',
            new_name='qr_code_path',
        ),
    ]
