# Generated by Django 5.1.1 on 2024-10-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0004_qrcodedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCodeData',
        ),
    ]
