# Generated by Django 5.1.1 on 2024-10-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0005_delete_qrcodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='qr_code',
            field=models.TextField(default='6yh8vhjivfj8hjif'),
            preserve_default=False,
        ),
    ]
