# Generated by Django 5.1.1 on 2024-10-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0006_guest_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='qr_code',
        ),
    ]
