# Generated by Django 5.1.1 on 2024-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_list', '0007_remove_guest_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='registration_code',
            field=models.CharField(default='emOK887GYe', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
